### ISSUE TITLE
Smart Contracts: Add several jumps

### ISSUE THREAD

**Issue by gianalarcon** [The-Marquis-Gaming/checkers-dojo#10]
## Issue Overview

- Currently we just implement simple jumps for normal pieces and for queen/king. 

## Proposed Solutions or Ideas

- Implement several successive jumps in a straight or zigzag forward direction, you `must` make all of them. Implement for normal pieces and for queen/king
- Implement required tests.

**Comment by CollinsC1O** [comment]
Can I take care of this issue?

**Comment by Bosun-Josh121** [comment]
I am applying to this issue via OnlyDust platform.

My background and how it can be leveraged:

software engineering background, backend & smart contract dev with contribution to similar tasks(https://app.onlydust.com/u/Josh-121)(mancala) looking to make first contribution on this project

I'm willing to take on this task, have some experience in developing board games, I
work on feedback & recommendation ensuring contact.

**Comment by Supa-mega** [comment]
Could I take a shot at this?

**Comment by manlikeHB** [comment]
Hi, I am a Cairo developer with great experience contributing to lots of Cairo code base. 

I will go through the codebase then propose a solution and implement.

ETA - 4 days

**Comment by ShantelPeters** [comment]
I am web3 developer with strong background in Cairo 
Can I please attempt this issue?

**Comment by SoarinSkySagar** [comment]
May I work on this @gianalarcon?

I am a cairo developer with extensive experience and a regulr contributor at @keep-starknet-strange.

eta: 3 days

**Comment by baitcode** [comment]
Hi! I'm a cairo dev with passion for gamedev. I'd love to tackle the issue as I've wanted to get more experience with dojo. 
I'm unsure If I understood task correctly.
I've glanced through code quickly and would propose to add new api for sequential jumps that allows to build jump path checking valid jumps one by one and then commit to it.
Otherwise I can update is jump possible method to include all coordinates that piece can get to through sequence of moves. And then implement the movement.

**Comment by saimeunt** [comment]
Hey I'd like to implement this one, I'll implement the new feature which is enabling successive jumps in a single player turn, and add all the necessary tests.

**Comment by Bosun-Josh121** [comment]
> I am applying to this issue via OnlyDust platform.
> 
> My background and how it can be leveraged:
> 
> software engineering background, backend & smart contract dev with contribution to similar tasks(https://app.onlydust.com/u/Josh-121)(mancala) looking to make first contribution on this project
> 
> I'm willing to take on this task, have some experience in developing board games, I work on feedback & recommendation ensuring contact.

https://app.onlydust.com/u/Bosun-Josh121

**Comment by ikemHood** [comment]
Can I take this from here?

I have 1 year experience in game development, and 2+ years in smart contract development, 
I would modify the current simple jumps to allow for all possible checkers piece movements, 

1. Regular pieces:
- Move diagonally forward one square
- Jump diagonally forward over enemy pieces

2. Kings/Queens:
- Move diagonally in any direction (forward or backward)
- Jump diagonally in any direction over enemy pieces

I would make sure to validate the movement steps, check if the jumps are available.
Then, identify all possible jump scenarios
- Single jump
- Double jump (straight line or zigzag)
- Triple+ jumps (combinations of straight and zigzag)

Test cases would cover edge cases like when the piece is at the edge of the board

**Comment by kfastov** [comment]
I am a blockchain developer with experience in Cairo
I would add a method (or modify an existing one) to accept an array of jumps instead of a single one, checking it every jump is correct, and then modify the game flow and tests to match this logic. Also existing checks will be modified to check that all possible jumps are done.

**Comment by tekkac** [comment]
Ahoy, interested in this issue.

**Comment by gianalarcon** [comment]
all your @kfastov. I suggest to wait until issue #6 get merged. Then you can start. Thanks!

**Comment by kfastov** [comment]
@gianalarcon Thanks!

**Comment by gianalarcon** [comment]
all your @saimeunt. I suggest to wait until issue https://github.com/The-Marquis-Gaming/checkers-dojo/issues/6 get merged. Then you can start. Thanks!

**Comment by gianalarcon** [comment]
Hi @saimeunt 
Please pull the latest commit from the `develop` branch. Now you're ready to work on this issue.
Thanks!

**Comment by gianalarcon** [comment]
Hi @saimeunt. Any updates on this? We expect at least a draft PR within the upcoming hours. Thanks!

**Comment by saimeunt** [comment]
@gianalarcon Hey thanks for the notice, still working on the issue, I'll get a draft PR ready later today.

**Comment by joeperpetua** [comment]
GM, available to work on this!

**Comment by saimeunt** [comment]
@gianalarcon just woke up to see my issue reassigned and my work discarded although it contains a bugfix, I was almost done and planned to finish it today, this is rude tbh.

**Comment by gianalarcon** [comment]
closed with #17
