### ISSUE TITLE
Upgrade and Adapt Checker Integration with Controller

### ISSUE THREAD

**Issue by Nadai2010** [The-Marquis-Gaming/checkers-dojo#11]
# Issue Overview:

Checker has integrated connection to the cartridge controller using a [useControllerAccount.tsx](https://github.com/The-Marquis-Gaming/checkers-dojo/blob/develop/client/src/hooks/useControllerAccount.tsx). However, it is not prepared to work as a connector for Checker, as shown in the [React integration example](https://docs.cartridge.gg/controller/examples/react#integrating-with-starknetprovider). Currently, connection and disconnection are handled directly within the button. This issue is not related to Checker and involves the following:

---

### 0. **Update dojo latest version**
- Bump to dojo v1.0.3

### 1. **Integrate Controller v0.5.1**
- Update Checker to use the latest version of [Controller 0.5.1](https://github.com/cartridge-gg/controller/blob/main/packages/controller/package.json#L3).
- Refactor `useControllerAccount.tsx` or the necessary files to act as a connector, adapting it to the Checker flow.

### 2. **Remove Burner connection logic**
- Remove the connection logic to create burners [`CreateBurner.tsx`](https://github.com/The-Marquis-Gaming/checkers-dojo/blob/develop/client/src/connector/CreateBurner.tsx).
- Ensure existing functionality such as `(userName, isConnected...)` in the [ControllerButton.tsx](https://github.com/The-Marquis-Gaming/checkers-dojo/blob/develop/client/src//ControllerButton.tsx#L5) connector continues to work and is integrated into the game flow.

### 3. **Integrate SC Policies and Functions**
- Incorporate the [policies](https://github.com/The-Marquis-Gaming/checkers-dojo/blob/develop/client/src/hooks/useControllerAccount.tsx#L18) with the following Checker SC functions [(create_lobby, join_lobby, spawn, can_choose_piece, move_piece....)](https://github.com/The-Marquis-Gaming/checkers-dojo/blob/7af812a08ea8048952766e55054e8ad999e82e92/dojo-starter/src/systems/actions.cairo#L66)
- Review any changes to new SC issues to ensure compatibility with policies and their correct functionality within the controller integration.

### 4. **Configure ControllerOptions**
- Refactor the `ControllerOption` configuration found in [useControllerAccount.tsx](https://github.com/The-Marquis-Gaming/checkers-dojo/blob/develop/client/src/hooks/useControllerAccount.tsx#L29) to support **Slot** and **Sepolia** networks.

---

## **Test Environment**
1. Start Katana and deploy SC following the quickstart steps described in the [README](https://github.com/The-Marquis-Gaming/checkers-dojo/tree/develop?tab=readme-ov-file#quick-start-guide) file.
2. A recommendation Set up an environment for testing, but you can use others if you prefer:
- Use **Chrome** with **ngrok** enabled.
- Run the application with `ngrok http 5173`.
- Use the generated link `http://.....ngrok.io` to access the Application Controller and perform a registration and login with WebAuth options.
3. Verify the complete flow Controller & Checker:
- Policy enforcement.
- Connection and disconnection.
- SC (interactions, e.g. `create_lobby`, `join_lobby`, `move_piece`, etc.).

**Comment by od-hunter** [comment]
Hi @Nadai2010 , can I work on this please? Please give me the opportunity, I’m ready to work please

**Comment by petersdt** [comment]
Can I try solving this issue?

**Comment by Gianfranco99** [comment]
Hi @Nadai2010 I already implemented the controller in others repos, I can do it here also!

**Comment by Gianfranco99** [comment]
Hi @Nadai2010 I already implemented the controller in others repos, I can do it here also!

**Comment by Jemiiah** [comment]
Hello @Nadai2010 can i take this issue up please, I'd know how to go about it

**Comment by suhas-sensei** [comment]
I'd love to work on this! We recently integrated the controller for a project in gamejam.
