### ISSUE TITLE
Smart Contracts: Bump to dojo v1.0.8

### ISSUE THREAD

**Issue by gianalarcon** [The-Marquis-Gaming/checkers-dojo#20]
## Issue Overview

1. Bump to dojo v1.0.8
2. Make sure all tests pass
3. Explore new features of v1.0.8 and add it to the contracts

**Comment by nonso7** [comment]
May I handle this issue?

**Comment by ryzen-xp** [comment]
Hi, 
I am proficient Blockchain developer  expert in Cairo , Rust and Solidity  and also in web development.
I have  contributed many cairo ,rust  projects like chainevents , arkprojects ,dojo  etc  .   please /assign  this issue .
Thank You

**Comment by Supa-mega** [comment]
Can I contribute to this one?

**Comment by SoarinSkySagar** [comment]
May I work on this one @gianalarcon?

eta: 3 days

**Comment by jaiminRaiyani** [comment]
I’d like to work on this.

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by ShantelPeters** [comment]
May I handle this issue?

**Comment by beeguy74** [comment]
Hi, I am a beginner Cairo developer from Paris.
I closed one task for you on 10 ODHACK.
I will check the new features of v1.0.5 and make sure that everything works fine.
I don't promise to finish the issue quickly But I intend to do a decent job and at least do the draft PR within 48 hours.
Could I try solving this?

**Comment by gianalarcon** [comment]
All yours @ryzen-xp .  Please test your implementation thoroughly before submitting it for review. We expect your draft PR within the next 24 hours. 
Note: This is an **NON-REWARDED** issue. Please refer to the OD platform/team for more details.
Create your onw branch based on `develop` branch and send your PR to `develop` branch  as well.

**Comment by gianalarcon** [comment]
Hi @ryzen-xp . Any updates on this？

**Comment by ryzen-xp** [comment]
Hello @gianalarcon  , Sorry  for delay   I am  working on this issue

**Comment by ryzen-xp** [comment]
Sorry @gianalarcon , I am busy in College exam .

**Comment by beeguy74** [comment]
I still can take it, will finish it until Sunday )

**Comment by gianalarcon** [comment]
Would you like to try? @jaiminRaiyani @beeguy74 @nonso7

**Comment by tasneemtoolba** [comment]
I'd love to give this a go.

**Comment by gianalarcon** [comment]
Hi @tasneemtoolba we are expecting a draft PR soon pls. Thanks!
