### ISSUE TITLE
Reconciliate develop branch with main branch

### ISSUE THREAD

**Issue by gianalarcon** [The-Marquis-Gaming/checkers-dojo#21]
## Issue Overview

- There has been many PRs that got merged, need to re-conciliate them with main branch

## Proposed Solutions or Ideas

1. Code Integration
    - Pull latest changes from main branch
    - Identify and resolve any merge conflicts
    - Ensure all recent PRs/commit of develop branch are properly integrated
    - Verify code consistency across all merged components
2. Testing & Quality Assurance
    - Verify functionality of all integrated features
    - Test system performance after integration
    - Document any new bugs or issues discovered
3. Edge Case Analysis
    - Review and test critical user paths
    - Verify error handling and recovery

**Comment by kallis312** [comment]
Could I be assigned to this?

**Comment by codebestia** [comment]
Can i be assigned this issue?
I am a full stack developer with ample experience in building innovative and scalable solutions. on the blockchain side, i bring expertise in DAPP development, smart contract design and integration of several chains technology.

I will thoroughly implement all the proposed solutions  if assigned

**Comment by Thibrac** [comment]
Can I attempt this issue?

**Comment by jedstroke** [comment]
Can I take this from here?

**Comment by Jagadeeshftw** [comment]
Hi,  
I’d love to work on this issue as I have strong experience in developing secure and efficient smart contracts using Cairo and deploying them on StarkNet. Please assign this to me, and I’ll ensure to deliver a robust and high-quality PR within 12-24 hours.

**Comment by greatest0falltime** [comment]
Hi,  

I’d be thrilled to work on this issue as I have extensive experience with Cairo programming and building decentralized applications on StarkNet.  

ETA:  
I expect to have a working solution ready within the next 24 hours. Kindly let me know if I can proceed!   

Looking forward to contributing!

**Comment by 1nonlypiece** [comment]
Hi,  
I’d like to work on this issue as I have experience with Cairo and building on StarkNet, including writing and optimizing smart contracts.  

ETA:  
I estimate completing this task in about 12-24 hours. Let me know if I can get started!

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by ShantelPeters** [comment]
I'd love to work on this!

**Comment by pheobeayo** [comment]
May I pick this up?
I am a Web3 front-end developer skilled in technical documentation and software development. I greatly understand technologies like JavaScript, Typescript, Cairo, Rust and Solidity. I have contributed successfully to open-source projects like Stark Quest and Speedrun scaffold-stark
I will fix the issue by 
- testing the integrated features
- Verify the codes 
- Merge to the main branch if conditions are satisfied

**Comment by Jake1698** [comment]
can I try this one pls?

**Comment by Amarjeet325** [comment]
Could I take a shot at this?

**Comment by codeZe-us** [comment]
Can I work on this?

**Comment by Supa-mega** [comment]
Can I work on this, please?

**Comment by gianalarcon** [comment]
All yours @Jake1698.  Please test your implementation thoroughly before submitting it for review. We expect your draft PR within the next 24 hours.
