### ISSUE TITLE
Refactor core logic, models and traits.

### ISSUE THREAD

**Issue by Gianfranco99** [The-Marquis-Gaming/checkers-dojo#23]
Description
To improve code maintainability, scalability, and readability, we propose a refactor of the current implementation to adopt a more modular structure. The primary focus will be to:

1- Migrate logic related to specific models into their respective traits
2-Restructure models into separate directories

Example Refactor

```
#[generate_trait]

 impl PieceImpl of PieceTrait {
         fn new(
             session_id: u64,
             row: u8,
             col: u8,
             player: ContractAddress,
             position: Position,
         ) -> Piece {
                   Piece {
                       session_id,
                       row,
                       col,
                       player,
                       position,
                       is_king: false,
                       is_alive: true,
                   }
         }
```

**Comment by ryzen-xp** [comment]
Hi ,
 I am proficient Blockchain developer  expert in Cairo , Rust and Solidity  and also in web development.
I have  contributed many cairo ,rust  projects like chainevents , arkprojects , dojo etc  .   please /assign  this issue .
Thank You

**Comment by manlikeHB** [comment]
Hi, I am a Cairo and Rust Developer with great experience contributing to lots of amazing projects. Can I work on this?

**Comment by Supa-mega** [comment]
I’m interested in this one.

**Comment by SoarinSkySagar** [comment]
May I work on this one @gianalarcon? 

eta: 3/4 days

**Comment by BraCR10** [comment]
Hi maintainers I'm BRACR10 from DOJO coding community, I would like to work on this issue because I have experience with cairo and dojo engine, I consider that I can perform the task and organize the code as best as possible, Also, I will make sure to contact you in case of any doubt during the refactoring and implement some test if necessary.

**Comment by jimenezz22** [comment]
Hi, I’d like to work on this issue! I’m member of Dojo Coding Community and I have extensive experience working with Cairo, including contributions to projects like **CairoLint**, utilizing **Dojo Engine** to create on-chain games at **ByteBuilders**, completing Cairo-based quests with **Node Guardians**, and teaching a Cairo class at a **Starknet bootcamp**

### My Approach:

1. **Modularization of Logic**
    - Migrate logic specific to each model into its respective trait to ensure better separation of concerns.
    - Use `#[generate_trait]` and trait implementations to encapsulate functionality, as shown in the provided example.
2. **Restructuring Models**
    - Move each model into its dedicated directory to improve maintainability and scalability.
    - Organize related files (e.g., traits, implementations, and tests) within these directories for a clean and intuitive structure.
3. **Code Quality and Consistency**
    - Ensure all changes maintain compatibility with the current codebase and adhere to established standards.
    - Simplify redundant logic where applicable, leveraging reusable patterns.
4. **Testing and Validation**
    - Validate the refactor with unit tests to confirm that existing functionality remains intact.
    - Ensure proper integration of the new modular structure by running integration tests across the codebase.

ETA: 3 days maximum in the worst case scenario.

**Comment by anonfedora** [comment]
I am Eleazar a fullstack blockchain developer,

1. Will create directories for interfaces, types etc. as required
2. Will move the logic to the required file in the required directory as required in order to achieve modularity for easy scalability, maintenance and readability.

**Comment by wheval** [comment]
May I work on this?
I have experience working with Cairo.

ETA is 1 day.

**Comment by Jagadeeshftw** [comment]
Hi,  
I’d love to work on this issue as I have strong experience in developing secure and efficient smart contracts using Cairo and deploying them on StarkNet. Please assign this to me, and I’ll ensure to deliver a robust and high-quality PR within 12-24 hours.

**Comment by greatest0falltime** [comment]
Can I take care of thiHi,  

I’d be thrilled to work on this issue as I have extensive experience with Cairo programming and building decentralized applications on StarkNet.  

ETA:  
I expect to have a working solution ready within the next 24 hours. Kindly let me know if I can proceed!   

Looking forward to contributing!  s issue?

**Comment by 1nonlypiece** [comment]
Hi,  
I’d like to work on this issue as I have experience with Cairo and building on StarkNet, including writing and optimizing smart contracts.  

ETA:  
I estimate completing this task in about 12-24 hours. Let me know if I can get started!

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by ShantelPeters** [comment]
I'd like to take this issue.

**Comment by coxmars** [comment]
Hi @Gianfranco99, I'm a software developer with 2+ years of experience and I have worked with backend technologies such as Cairo, Java, C# and frontend with React, NextJS, JS/TS. Also, I'm a member of the Dojo Coding community here in CR and I have made contributions in Cairo VM Go, Cairo VM TS, Cairo Lints etc. Likewise, I’m a Cairo developer working in ByteBuildersLabs creating on-chain games using the Dojo framework.

This is my approach:

- Review the current codebase to identify logic for migration and necessary restructuring.
- Refactor model-specific logic into traits for modularity.
- Organize models into directories for improved scalability and readability.
- Validate changes with unit tests to ensure consistency and maintainability.

Estimated Time: 3 days

**Comment by Amarjeet325** [comment]
Could I take a shot at this?

**Comment by DuendexCR** [comment]
May I be assigned to this?

**Comment by gianalarcon** [comment]
All yours @coxmars .  Please test your implementation thoroughly before submitting it for review. We expect your draft PR within the next 24 hours. 
Create your onw branch based on `develop` branch and send your PR to `develop` branch  as well.

**Comment by coxmars** [comment]
> All yours @coxmars . Please test your implementation thoroughly before submitting it for review. We expect your draft PR within the next 24 hours. Create your onw branch based on `develop` branch and send your PR to `develop` branch as well.

Thanks sir, I will do it asap 🫡

**Comment by emarc99** [comment]
May I pick this up?

**Comment by gianalarcon** [comment]
> May I pick this up?

you abandoned the other [issue](https://github.com/The-Marquis-Gaming/themarquis-ui/pull/106) I assigned to you and now you asking to work on this one? You are doing your best in order to get blacklisted and reported with OnlyDust managers
