### ISSUE TITLE
Configure mkcert dependence in vite.config

### ISSUE THREAD

**Issue by Gianfranco99** [The-Marquis-Gaming/checkers-dojo#24]
## Issue Overview:

Currently we must use ngrok to be able to use the cartridge controller, with this dependency installed and configured correctly we should not have problems and the controller could be used without having to use ngrok

## Proposed solution:

You can ask for support within the [discord channel.](https://discord.com/channels/954866867376357397/1245396743210668135) 

You can see a correct implementation here https://github.com/broody/number-challenge/blob/main/vite.config.ts

**Comment by ShantelPeters** [comment]
Please can I be assigned to this issue?

**Comment by caxtonacollins** [comment]
I am a Full Stack Developer with two years of professional experience, specializing in web3. I have strong background in blockchain and extensive experience in Next.js/React, TypeScript, Cairo and Rust.

I will love to take care of this.

**Comment by Supa-mega** [comment]
Let me try this one! first time contributor

**Comment by Jagadeeshftw** [comment]
I’d like to resolve this.

**Comment by Amarjeet325** [comment]
I’m interested in this one.

**Comment by kcmikee** [comment]
Hi, I'm Mike, can I handle this task?
I have worked on couple of project using vite and have resolved similar issue

ETA: 1 day

**Comment by tosinmoses384** [comment]
I will address the issue in the followings ways:

1. check mkcert installation
2. generate certificates
3. update vite config
4. run vite
5. access local server

**Comment by Dorcas18** [comment]
Can I take this issue?

**Comment by Nityam573** [comment]
Can I take this issue?

**Comment by sonkiee** [comment]
Is it okay if I take this?

**Comment by gianalarcon** [comment]
Hi Sir, any updates on this? @Jagadeeshftw
