### ISSUE TITLE
Refactor core logic, models and traits

### ISSUE THREAD

**Issue by gianalarcon** [The-Marquis-Gaming/checkers-dojo#35]
# Issue | Checkers

## 1. Type of Issue

- [ ] Bug  
- [ ] Feature Request  
- [x] Enhancement  
- [ ] Documentation  
- [ ] Other  

---

## 2. Brief Description  

Description
To improve code maintainability, scalability, and readability, we propose a refactor of the current implementation to adopt a more modular structure. The primary focus will be to:

1- Migrate logic related to specific models into their respective traits
2-Restructure models into separate directories

Example Refactor

```
#[generate_trait]

 impl PieceImpl of PieceTrait {
         fn new(
             session_id: u64,
             row: u8,
             col: u8,
             player: ContractAddress,
             position: Position,
         ) -> Piece {
                   Piece {
                       session_id,
                       row,
                       col,
                       player,
                       position,
                       is_king: false,
                       is_alive: true,
                   }
         }
```

---

## 3. Current Behavior  
  

---

## 4. Expected Behavior  
  

---

## 5. Steps to Reproduce (For Bugs)

1. Step 1  
2. Step 2  
3. Step 3  

---

## 6. Evidence (Optional)  

---

## 7. Additional Context (Optional)  

---

**Comment by emarc99** [comment]
Could I handle this issue please.

**Comment by RajeshRk18** [comment]
Can I take up this one? I have experience writing Cairo contracts. Here is the recent PR I made for ERC-4907:

https://github.com/Flex-NFT-Marketplace/Flex-Marketplace-Contract/pull/153

**Comment by Gianfranco99** [comment]
It's your all yours @RajeshRk18

**Comment by RajeshRk18** [comment]
> It's your all yours @RajeshRk18  

@Gianfranco99 Thanks!! This is a paid issue right?

**Comment by gianalarcon** [comment]
> > It's your all yours @RajeshRk18
> 
> @Gianfranco99 Thanks!! This is a paid issue right?

Yes!

**Comment by gianalarcon** [comment]
> > It's your all yours @RajeshRk18
> 
> @Gianfranco99 Thanks!! This is a paid issue right?

We expect a draft PR within next 24 hours Sir. Create your branch based on `develop` branch

**Comment by RajeshRk18** [comment]
> > > It's your all yours @RajeshRk18
> 
> > 
> 
> > @Gianfranco99 Thanks!! This is a paid issue right?
> 
> 
> 
> We expect a draft PR within next 24 hours Sir. Create your branch based on `develop` branch

Sure!

**Comment by RajeshRk18** [comment]
@gianalarcon Made a [PR](https://github.com/The-Marquis-Gaming/checkers-dojo/pull/36)

**Comment by gianalarcon** [comment]
Closed
