### ISSUE TITLE
Bump to dojo v1.0.9

### ISSUE THREAD

**Issue by gianalarcon** [The-Marquis-Gaming/checkers-dojo#39]
# Issue | Checkers

## 1. Type of Issue

- [ ] Bug  
- [x] Feature Request  
- [ ] Enhancement  
- [ ] Documentation  
- [ ] Other  

---

## 2. Brief Description  

Bump to dojo v1.0.9
---

## 3. Current Behavior  
  
Current `develop` branch not working as expected

---

## 4. Expected Behavior  
  
Full gameplay flow should workm, with controller or burner wallet

---

## 5. Steps to Reproduce (For Bugs)

1. Step 1  
2. Step 2  
3. Step 3  

---

## 6. Evidence (Optional)  

---

## 7. Additional Context (Optional)  

---

**Comment by 847850277** [comment]
Can I attempt this issue?

**Comment by gianalarcon** [comment]
Hi @847850277 , we just closed this PR, we will open few more issues, you can contribute there as well, I will let you know

**Comment by gianalarcon** [comment]
if you interested, you can apply here sir https://github.com/The-Marquis-Gaming/checkers-dojo/issues/38
@847850277

**Comment by 847850277** [comment]
> if you interested, you can apply here sir #38 @847850277

Hi,Sir, I am good at the backend, but I am still a novice in the frontend. 🙏

**Comment by gianalarcon** [comment]
Cool find me on discord pls https://discord.gg/ZWkWeypnzv. 我也是一个 backend guy hehe
