### ISSUE TITLE
Improve project workflows

### ISSUE THREAD

**Issue by gianalarcon** [The-Marquis-Gaming/checkers-dojo#41]
# Issue | Checkers

## 1. Type of Issue

- [ ] Bug  
- [ ] Feature Request  
- [x] Enhancement  
- [ ] Documentation  
- [ ] Other  

---

## 2. Brief Description  

Current workflows tests the dojo contracts,but need to improve the way of installation. At the same time we are not checking the code format

## 3. Current Behavior  
  
1. Current version of dojo is hardcoded
2. Missing scarb fmt or any linter for dojo/cairo code
---

## 4. Expected Behavior  
  
 1. it should install the dojo version from .tool-versions.toml file
 2. Implent the script to check dojo code format
---
---

## 4. Proposed Solution (Optional)  

Take as reference this workflows: 
- [Eternum](https://github.com/BibliothecaDAO/eternum/tree/next/.github) 
- [zKube](https://github.com/z-korp/zkube/blob/main/.github/workflows/ci.yaml)

**Comment by No-bodyq** [comment]
I'd like to take this issue.

**Comment by gianalarcon** [comment]
Cool. thanks for you help Sir. If you have any questions pls find us on [discord](https://discord.gg/bWuQFHHA)
