### ISSUE TITLE
Smart Contracts: Bump to dojo v1.0.1

### ISSUE THREAD

**Issue by gianalarcon** [The-Marquis-Gaming/checkers-dojo#6]
## Issue Overview

1. Bump to dojo v1.0.1
2. Make sure all tests pass
3. Use new features of v1.0.1 as [world.write_models](https://github.com/dojoengine/dojo/blob/f6659db7cf081ac4071b2c2e9555fad0eed12210/crates/dojo/core-cairo-test/src/tests/world/storage.cairo#L33). Implement this new feature on [`initialize_player_pieces`](https://github.com/The-Marquis-Gaming/checkers-dojo/blob/7af812a08ea8048952766e55054e8ad999e82e92/dojo-starter/src/systems/actions.cairo#L238)
4. Improve tests to use `write_models` and `read_models`
5. Refactor `fn spawn()` to become internal function. It shouldn't be external function

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by joeperpetua** [comment]
GM, would love to work on this issue, have been working in multiple projects powered by Dojo.

**Comment by Supa-mega** [comment]
May I be assigned to this?

**Comment by ShantelPeters** [comment]
May I pick this up?

**Comment by SoarinSkySagar** [comment]
May I work on this @gianalarcon?

I am a cairo developer with extensive experience and a regulr contributor at @keep-starknet-strange.

eta: 3 days

**Comment by gianalarcon** [comment]
All yours @joeperpetua. We expected is issue to be solved soon. Remember that you have to create your branch based on our develop branch and your PR should point to our develop branch. Not our main branch

**Comment by gianalarcon** [comment]
Closed with #12
