### ISSUE TITLE
Smart Contracts: Enable session_id

### ISSUE THREAD

**Issue by gianalarcon** [The-Marquis-Gaming/checkers-dojo#7]
## Issue Overview

- Currently session_id is [hardcoded](https://github.com/The-Marquis-Gaming/checkers-dojo/blob/7af812a08ea8048952766e55054e8ad999e82e92/dojo-starter/src/systems/actions.cairo#L75)

## Proposed Solutions or Ideas
- Implement dynamic session_id, it can be genereated using the counter we have [there](https://github.com/The-Marquis-Gaming/checkers-dojo/blob/7af812a08ea8048952766e55054e8ad999e82e92/dojo-starter/src/systems/actions.cairo#L69) . Note: Take the counter just as a reference. You can provide your own implementation
- Create tests for session_id

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by joeperpetua** [comment]
GM, would love to work on this issue, have been working in multiple projects powered by Dojo.

**Comment by Hoossayn** [comment]
Hi, would like to take this on

**Comment by Supa-mega** [comment]
Can I try solving this issue?

**Comment by CollinsC1O** [comment]
Hello @gianalarcon I'm a front-end and a blockchain. Would love to tackle this!

**Comment by GideonBature** [comment]
Could I be assigned to this?

My name is Gideon Bature, a Software Engineer with experience building Starknet based smart contracts, using Cairo. If given this issue, I should be able to send my first PR within 72 hrs. 

Thank you!

**Comment by ShantelPeters** [comment]
Can I take this from here?

**Comment by SoarinSkySagar** [comment]
May I work on this @gianalarcon?

I am a cairo developer with extensive experience and a regulr contributor at @keep-starknet-strange.
I will make the session_id dynamic and take inspiration from the link you provided. I will also create tests with complete coverage and edge cases.

eta: 3 days

**Comment by ryzen-xp** [comment]
Hi, I am proficient Blockchain developer  expert in Cairo , Rust and Solidity  and also in web development.
I have  contributed many Rust ,Cairo  projects like chainevents , arkprojects , starknet  etc  .   please /assign  this issue .
Thank You

**Comment by beeguy74** [comment]
Can I be assigned to this? i am from starkent.dart chat =)

**Comment by gianalarcon** [comment]
All yours @beeguy74 . I suggest to wait until issue #6 get merged. Then you can start. Thanks!

**Comment by gianalarcon** [comment]
Hi @beeguy74,
Please pull the latest commit from the `develop` branch. Now you're ready to work on this issue.
Thanks!

**Comment by gianalarcon** [comment]
Hi @beeguy74  . Any updates on this? We expect at least a draft PR within the upcoming hours. Thanks!

**Comment by beeguy74** [comment]
Hi. i'll do the draft this night.

**Comment by gianalarcon** [comment]
closed with #13
