### ISSUE TITLE
Smart Contracts: Enable custom events

### ISSUE THREAD

**Issue by gianalarcon** [The-Marquis-Gaming/checkers-dojo#8]
## Issue Overview

- Currently we defined custom [events](https://github.com/The-Marquis-Gaming/checkers-dojo/blob/7af812a08ea8048952766e55054e8ad999e82e92/dojo-starter/src/systems/actions.cairo#L35) but probably we dont emit them in all the places.
- There is no a event for the case when a piece become a King/Queen
- Bump to dojo [v1.0.2](https://github.com/dojoengine/dojo/releases/tag/v1.0.2)
## Proposed Solutions or Ideas

- Emit these events and add create the missing ones
- Create tests to catch events

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by joeperpetua** [comment]
GM, would love to work on this issue, have been working in multiple projects powered by Dojo.

**Comment by martinvibes** [comment]
Can I take care of this issue?
i'm a frontend dev and a blockchain dev please kindly assign :)

**Comment by codebestia** [comment]
Could i work on this?
I am new here and i will love to contribute to this project

**Comment by Supa-mega** [comment]
May I be assigned to this?

**Comment by CollinsC1O** [comment]
Hello @gianalarcon I'm a front-end and a blockchain. I will love to work on this

**Comment by manlikeHB** [comment]
Hi, I am a Cairo developer with great experience contributing to previous OD Hack. Let me work on this.

**Comment by Gerson2102** [comment]
---

### Hey! I'm Gerson. 👋

Member of **Dojo Coding**. I have contributed before to other projects like:

- `kakarot-rpc`
- `kakarot-ssj`
- `ef-tests`
- `Raito`
- `Starknet-Phone`
- `Madara`
- `stark-cairo-nodes`

Can I work on this issue?

Check my OnlyDust profile, I've contributed to many projects: [Profile](https://app.onlydust.com/u/Gerson2102)

---

### Plan to Solve the Issue:

1. **Study the codebase** to understand the current structure and functionality.
2. **Understand the problem** that needs to be solved by thoroughly reading the issue details.
3. **Leverage all provided resources** within the issue to get a better grasp of the task at hand.
4. If I encounter roadblocks, I will **ask questions ASAP** in the Telegram group to move forward effectively.
5. **I will open a PR** and wait for ur feedback

---

**Comment by GideonBature** [comment]
Is it okay if I take this?

My name is Gideon Bature, a Software Engineer with experience building Starknet based smart contracts, using Cairo. If given this issue, I should be able to send my first PR within 72 hrs. 

Thank you!

**Comment by SoarinSkySagar** [comment]
May I work on this @gianalarcon?

I am a cairo developer with extensive experience and a regulr contributor at @keep-starknet-strange.

eta: 3 days

**Comment by ryzen-xp** [comment]
Hi, I am proficient Blockchain developer  expert in Cairo , Rust and Solidity  and also in web development.
I have  contributed many Rust ,Cairo  projects like chainevents , arkprojects , starknet  etc  .   please /assign  this issue .
Thank You

**Comment by ryzen-x** [comment]
Hi, I am proficient Blockchain developer  expert in Cairo , Rust and Solidity  and also in web development.
 please /assign  this issue .
Thank You

**Comment by ptisserand** [comment]
I'm a cairo developer with several contributions to ark project, art peace, shinigami, konoha ...
For this issue I will add event emission and associated unit test.

**Comment by gianalarcon** [comment]
All yours @ptisserand . I suggest to wait until issue #6 get merged. Then you can start. Thanks!

**Comment by gianalarcon** [comment]
Hi @ptisserand ,
Please pull the latest commit from the `develop` branch. Now you're ready to work on this issue.
Thanks!

**Comment by bitfalt** [comment]
Closed by #16
